# Generated by Django 5.0.1 on 2024-01-15 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco_id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='crud.endereco'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
